"""renamed recipient and sender fields

Revision ID: 09d0788a9f2d
Revises: 7cbd55c5c75c
Create Date: 2020-03-03 15:59:33.977644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09d0788a9f2d'
down_revision = '7cbd55c5c75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipient_data_2')
    op.drop_table('message_user_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_user_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=True),
    sa.Column('user_email', mysql.VARCHAR(collation='utf8_bin', length=120), nullable=True),
    sa.Column('role', mysql.VARCHAR(collation='utf8_bin', length=15), nullable=True),
    sa.Column('_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('_status', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_message_user_data_user_id_user'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('recipient_data_2',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['message_user_data.id'], name='fk_recipient_data_2_id_message_user_data'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='fk_recipient_data_2_message_id_message', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
