"""add dollar cost paid to review

Revision ID: 0e6888c3db4f
Revises: 6080f7591ef6
Create Date: 2019-10-30 07:50:32.672085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6888c3db4f'
down_revision = '6080f7591ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('price_paid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'price_paid')
    # ### end Alembic commands ###
