"""messages v4

Revision ID: 0f30f957698d
Revises: e94e80a00b04
Create Date: 2019-12-22 10:27:12.980539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f30f957698d'
down_revision = 'e94e80a00b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_message_from_id_user', 'message', type_='foreignkey')
    op.create_foreign_key(op.f('fk_message_sender_id_user'), 'message', 'user', ['sender_id'], ['id'])
    op.drop_column('message', 'from_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('from_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_message_sender_id_user'), 'message', type_='foreignkey')
    op.create_foreign_key('fk_message_from_id_user', 'message', 'user', ['from_id'], ['id'])
    op.drop_column('message', 'sender_id')
    # ### end Alembic commands ###
