"""post message update testing

Revision ID: 10edb68acf2c
Revises: eb93a5614217
Create Date: 2020-03-05 10:25:47.721340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10edb68acf2c'
down_revision = 'eb93a5614217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipient')
    op.drop_table('sender')
    op.alter_column('message', 'conversation_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('message_user', sa.Column('_role', sa.String(length=15), nullable=True))
    op.add_column('message_user', sa.Column('full_name', sa.String(length=128), nullable=True))
    op.add_column('message_user', sa.Column('message_id', sa.Integer(), nullable=True))
    op.add_column('message_user', sa.Column('read', sa.Boolean(), nullable=True))
    op.add_column('message_user', sa.Column('tag', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_message_user_read'), 'message_user', ['read'], unique=False)
    op.create_index(op.f('ix_message_user_tag'), 'message_user', ['tag'], unique=False)
    op.drop_index('ix_message_user__read', table_name='message_user')
    op.drop_index('ix_message_user__tag', table_name='message_user')
    op.create_foreign_key(op.f('fk_message_user_message_id_message'), 'message_user', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_column('message_user', '_read')
    op.drop_column('message_user', 'role')
    op.drop_column('message_user', '_tag')
    op.drop_column('message_user', '_full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_user', sa.Column('_full_name', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=True))
    op.add_column('message_user', sa.Column('_tag', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True))
    op.add_column('message_user', sa.Column('role', mysql.VARCHAR(collation='utf8_bin', length=15), nullable=True))
    op.add_column('message_user', sa.Column('_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_message_user_message_id_message'), 'message_user', type_='foreignkey')
    op.create_index('ix_message_user__tag', 'message_user', ['_tag'], unique=False)
    op.create_index('ix_message_user__read', 'message_user', ['_read'], unique=False)
    op.drop_index(op.f('ix_message_user_tag'), table_name='message_user')
    op.drop_index(op.f('ix_message_user_read'), table_name='message_user')
    op.drop_column('message_user', 'tag')
    op.drop_column('message_user', 'read')
    op.drop_column('message_user', 'message_id')
    op.drop_column('message_user', 'full_name')
    op.drop_column('message_user', '_role')
    op.alter_column('message', 'conversation_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_table('sender',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['message_user.id'], name='fk_sender_id_message_user'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='fk_sender_message_id_message'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('recipient',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['message_user.id'], name='fk_recipient_id_message_user'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='fk_recipient_message_id_message'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
