"""add lat and long

Revision ID: 3960580c1d4b
Revises: 
Create Date: 2019-07-11 12:21:50.357626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3960580c1d4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unknown', sa.Boolean(), nullable=True))
        batch_op.alter_column('_line1',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('zip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_address_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_unknown'), ['unknown'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_unknown'))
        batch_op.drop_index(batch_op.f('ix_address_longitude'))
        batch_op.drop_index(batch_op.f('ix_address_latitude'))
        batch_op.alter_column('zip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('_line1',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('unknown')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
