"""mid testing

Revision ID: 4666e90768f5
Revises: 3960580c1d4b
Create Date: 2019-09-04 16:37:36.923741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4666e90768f5'
down_revision = '3960580c1d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('sector_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('friendrequest', schema=None) as batch_op:
        batch_op.alter_column('date_sent',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('grouprequest', schema=None) as batch_op:
        batch_op.alter_column('date_sent',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_provider_email'), ['email'])
        batch_op.drop_index('ix_provider__name')
        batch_op.create_index(batch_op.f('ix_provider__name'), ['_name'], unique=False)
        batch_op.drop_index('ix_provider_email')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('fk_review_provider_id_provider', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_review_provider_id_provider'), 'provider', ['provider_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_review_provider_id_provider'), type_='foreignkey')
        batch_op.create_foreign_key('fk_review_provider_id_provider', 'provider', ['provider_id'], ['id'])

    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.create_index('ix_provider_email', ['email'], unique=1)
        batch_op.drop_index(batch_op.f('ix_provider__name'))
        batch_op.create_index('ix_provider__name', ['_name'], unique=1)
        batch_op.drop_constraint(batch_op.f('uq_provider_email'), type_='unique')

    with op.batch_alter_table('grouprequest', schema=None) as batch_op:
        batch_op.alter_column('date_sent',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('friendrequest', schema=None) as batch_op:
        batch_op.alter_column('date_sent',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('sector_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
