"""post messaging changes

Revision ID: 4cf73a3ea764
Revises: 0f30f957698d
Create Date: 2020-02-27 10:29:45.449475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf73a3ea764'
down_revision = '0f30f957698d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_category_provider_provider_id_provider', 'category_provider', type_='foreignkey')
    op.create_foreign_key(op.f('fk_category_provider_provider_id_provider'), 'category_provider', 'provider', ['provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_category_provider_provider_id_provider'), 'category_provider', type_='foreignkey')
    op.create_foreign_key('fk_category_provider_provider_id_provider', 'category_provider', 'provider', ['provider_id'], ['id'])
    # ### end Alembic commands ###
