"""subclass test

Revision ID: 7cbd55c5c75c
Revises: c8c1b223594e
Create Date: 2020-03-03 15:06:07.077648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cbd55c5c75c'
down_revision = 'c8c1b223594e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipient_data_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['message_user_data.id'], name=op.f('fk_recipient_data_2_id_message_user_data')),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_recipient_data_2_message_id_message'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipient_data_2'))
    )
    op.drop_index('fk_recipient_data_user_id_user', table_name='recipient_data')
    op.drop_table('recipient_data')
    op.add_column('user', sa.Column('role', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.create_table('recipient_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='fk_recipient_data_message_id_message', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_recipient_data_user_id_user', 'recipient_data', ['user_id'], unique=False)
    op.drop_table('recipient_data_2')
    # ### end Alembic commands ###
