"""remove provider.email index

Revision ID: 7fbf22742872
Revises: 3960580c1d4b
Create Date: 2019-07-11 15:20:42.683298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbf22742872'
down_revision = '3960580c1d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_provider_email'), ['email'])
        batch_op.drop_index('ix_provider_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.create_index('ix_provider_email', ['email'], unique=1)
        batch_op.drop_constraint(batch_op.f('uq_provider_email'), type_='unique')

    # ### end Alembic commands ###
