"""new db copy

Revision ID: 8e75fb301b58
Revises: 
Create Date: 2019-09-12 20:34:11.751443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e75fb301b58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('_telephone', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider')),
    sa.UniqueConstraint('_telephone', name=op.f('uq_provider__telephone')),
    sa.UniqueConstraint('email', name=op.f('uq_provider_email'))
    )
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider__name'), ['_name'], unique=False)

    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sector'))
    )
    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sector_name'), ['name'], unique=True)

    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('state_short', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_state'))
    )
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_state_short'), ['state_short'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('_email', sa.String(length=120), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('password_set_date', sa.Date(), nullable=True),
    sa.Column('_first_name', sa.String(length=64), nullable=False),
    sa.Column('_last_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user__email'), ['_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user__first_name'), ['_first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user__last_name'), ['_last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_password_set_date'), ['password_set_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_line1', sa.String(length=128), nullable=True),
    sa.Column('_line2', sa.String(length=128), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('_city', sa.String(length=64), nullable=False),
    sa.Column('unknown', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.CheckConstraint('_line1 IS NOT NULL OR unknown == 1', name='chk_line1unknown'),
    sa.CheckConstraint('provider_id IS NOT NULL OR user_id IS NOT NULL', name='chk_address_fks'),
    sa.CheckConstraint('zip IS NOT NULL OR unknown == 1', name='chk_zipunknown'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('fk_address_provider_id_provider'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], name=op.f('fk_address_state_id_state')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_address_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address'))
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address__city'), ['_city'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_unknown'), ['unknown'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_zip'), ['zip'], unique=False)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], name=op.f('fk_category_sector_id_sector')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=True)

    op.create_table('friendrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('date_sent', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name=op.f('fk_friendrequest_friend_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requestor_id'], ['user.id'], name=op.f('fk_friendrequest_requestor_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friendrequest'))
    )
    with op.batch_alter_table('friendrequest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendrequest_date_sent'), ['date_sent'], unique=False)

    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_name', sa.String(length=64), nullable=False),
    sa.Column('_description', sa.String(length=120), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name=op.f('fk_group_admin_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group'))
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group__name'), ['_name'], unique=True)

    op.create_table('user_friend',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name=op.f('fk_user_friend_friend_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_friend_user_id_user'))
    )
    op.create_table('category_provider',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_category_provider_category_id_category')),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('fk_category_provider_provider_id_provider'))
    )
    op.create_table('grouprequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('date_sent', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_grouprequest_group_id_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requestor_id'], ['user.id'], name=op.f('fk_grouprequest_requestor_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grouprequest'))
    )
    with op.batch_alter_table('grouprequest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grouprequest_date_sent'), ['date_sent'], unique=False)

    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('_description', sa.String(length=120), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('_comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_review_category_id_category')),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('fk_review_provider_id_provider'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_review_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_timestamp'), ['timestamp'], unique=False)

    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_user_group_group_id_group')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_group_user_id_user'))
    )
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('thumb', sa.String(length=120), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], name=op.f('fk_picture_review_id_review'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_picture'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture')
    op.drop_table('user_group')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_timestamp'))

    op.drop_table('review')
    with op.batch_alter_table('grouprequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grouprequest_date_sent'))

    op.drop_table('grouprequest')
    op.drop_table('category_provider')
    op.drop_table('user_friend')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group__name'))

    op.drop_table('group')
    with op.batch_alter_table('friendrequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendrequest_date_sent'))

    op.drop_table('friendrequest')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))

    op.drop_table('category')
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_zip'))
        batch_op.drop_index(batch_op.f('ix_address_unknown'))
        batch_op.drop_index(batch_op.f('ix_address_longitude'))
        batch_op.drop_index(batch_op.f('ix_address_latitude'))
        batch_op.drop_index(batch_op.f('ix_address__city'))

    op.drop_table('address')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_password_set_date'))
        batch_op.drop_index(batch_op.f('ix_user__last_name'))
        batch_op.drop_index(batch_op.f('ix_user__first_name'))
        batch_op.drop_index(batch_op.f('ix_user__email'))

    op.drop_table('user')
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_state_short'))
        batch_op.drop_index(batch_op.f('ix_state_name'))

    op.drop_table('state')
    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_name'))

    op.drop_table('sector')
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider__name'))

    op.drop_table('provider')
    # ### end Alembic commands ###
