"""add low_accuracy to address

Revision ID: b37ce618f530
Revises: 4cf73a3ea764
Create Date: 2020-02-27 14:13:02.595662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37ce618f530'
down_revision = '4cf73a3ea764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('low_accuracy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'low_accuracy')
    # ### end Alembic commands ###
