"""messages_v2

Revision ID: e80119a86721
Revises: 99cec7780657
Create Date: 2019-12-20 09:39:50.354586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e80119a86721'
down_revision = '99cec7780657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipient_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_recipient_data_message_id_message'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_recipient_data_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipient_data'))
    )
    op.create_index(op.f('ix_recipient_data_read'), 'recipient_data', ['read'], unique=False)
    op.create_index(op.f('ix_recipient_data_status'), 'recipient_data', ['status'], unique=False)
    op.drop_table('user_message')
    op.add_column('message', sa.Column('sender_status', sa.String(length=20), nullable=True))
    op.alter_column('message', 'conversation_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index(op.f('ix_message_sender_status'), 'message', ['sender_status'], unique=False)
    op.drop_index('ix_message_read', table_name='message')
    op.drop_column('message', 'read')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_message_read', 'message', ['read'], unique=False)
    op.drop_index(op.f('ix_message_sender_status'), table_name='message')
    op.alter_column('message', 'conversation_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('message', 'sender_status')
    op.create_table('user_message',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='fk_user_message_message_id_message'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_message_user_id_user'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_recipient_data_status'), table_name='recipient_data')
    op.drop_index(op.f('ix_recipient_data_read'), table_name='recipient_data')
    op.drop_table('recipient_data')
    # ### end Alembic commands ###
