"""minor changes to message

Revision ID: eb93a5614217
Revises: 3221bb685e15
Create Date: 2020-03-04 13:54:02.496998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb93a5614217'
down_revision = '3221bb685e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipient', 'message_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('fk_recipient_message_id_message', 'recipient', type_='foreignkey')
    op.create_foreign_key(op.f('fk_recipient_message_id_message'), 'recipient', 'message', ['message_id'], ['id'])
    op.alter_column('sender', 'message_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('fk_sender_message_id_message', 'sender', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sender_message_id_message'), 'sender', 'message', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sender_message_id_message'), 'sender', type_='foreignkey')
    op.create_foreign_key('fk_sender_message_id_message', 'sender', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sender', 'message_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(op.f('fk_recipient_message_id_message'), 'recipient', type_='foreignkey')
    op.create_foreign_key('fk_recipient_message_id_message', 'recipient', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recipient', 'message_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
