"""changed c status and is_not_active cols in provider suggestion

Revision ID: fc8082fd60a6
Revises: f55817922f06
Create Date: 2020-04-23 20:59:36.273405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc8082fd60a6'
down_revision = 'f55817922f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_provider', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('category_provider', 'provider_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('provider_suggestion', sa.Column('is_not_active', sa.Boolean(), nullable=True))
    op.add_column('provider_suggestion', sa.Column('status', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_provider_suggestion_status'), 'provider_suggestion', ['status'], unique=False)
    op.drop_index('ix_provider_suggestion_is_active', table_name='provider_suggestion')
    op.drop_column('provider_suggestion', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_suggestion', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_provider_suggestion_is_active', 'provider_suggestion', ['is_active'], unique=False)
    op.drop_index(op.f('ix_provider_suggestion_status'), table_name='provider_suggestion')
    op.drop_column('provider_suggestion', 'status')
    op.drop_column('provider_suggestion', 'is_not_active')
    op.alter_column('category_provider', 'provider_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('category_provider', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
